### ISSUE TITLE
Typo: read Revision ID gets Product ID

### ISSUE THREAD

**Issue by triffid** [Infineon/DPS310-Pressure-Sensor#1]
The issue seems to be here: [src/ifx_dps310.cpp#L827](https://github.com/Infineon/DPS310-Pressure-Sensor/blob/master/src/ifx_dps310.cpp#L827) - it should be [IFX_DPS310__REG_INFO_REV_ID](https://github.com/Infineon/DPS310-Pressure-Sensor/blob/master/src/util/ifx_dps310_consts.h#L59) instead of [IFX_DPS310__REG_INFO_PROD_ID](https://github.com/Infineon/DPS310-Pressure-Sensor/blob/master/src/util/ifx_dps310_consts.h#L51)

**Comment by mhollfelder** [comment]
Thank you very much, the typo has been corrected and a new release will be prepared.
