### ISSUE TITLE
DPS310-Pressure-Sensor-dps310 SPI error

### ISSUE THREAD

**Issue by p-brane** [Infineon/DPS310-Pressure-Sensor#28]
I began getting this error after a recent library update. I've read that the Arduino core library changed the way SPI is used and has broken some libraries. Is there and update to the `DPS310-Pressure-Sensor-dps310` v1.07 library to fix this? If not is there some examples of how to fix it?

I'm using the Grove High Precision Pressure Sensor (DPS310) on the MKR 1010 WiFi I2C bus. It's been working well until the library update. I'm using Arduino IDE 1.8.19 on Windows 10 21h1 and File -> Example -> DigitalPressureSensor. The DigitalPressureSensor library is v1.0.6 but is not used because the `DPS310-Pressure-Sensor-dps310` v1.07 is used. The SAMD Boards (32-bit ARM Cortex-Mo+ is version 1.8.13. The error is shown below.

```
D:\arduino\libraries\DPS310-Pressure-Sensor-dps310\src\DpsClass.cpp: In member function 'void DpsClass::begin(arduino::SPIClass&, int32_t, uint8_t)':
D:\arduino\libraries\DPS310-Pressure-Sensor-dps310\src\DpsClass.cpp:62:12: error: 'arduino::SPIClass {aka class arduino::HardwareSPI}' has no member named 'setDataMode'
  m_spibus->setDataMode(SPI_MODE3);
            ^~~~~~~~~~~
Multiple libraries were found for "Dps310.h"
 Used: D:\arduino\libraries\DPS310-Pressure-Sensor-dps310
 Not used: D:\arduino\libraries\DigitalPressureSensor
```

**Comment by enricocalore** [comment]
Hi,
I faced the same issue and I solved it modifying DpsClass.cpp with this quick and dirty solution:

```
// Comment these lines:
// m_spibus->begin();
// m_spibus->setDataMode(SPI_MODE3);

// Add this line in their place:
m_spibus->beginTransaction(SPISettings(14000000, MSBFIRST, SPI_MODE3));
```
p.s.
Other parts of the library may need further changes, I did not check all of them.

**Comment by p-brane** [comment]
Hi @enricocalore 
That seems to work. Thank you.
